### ISSUE TITLE
Welfare decomposition: technical efficiency

### ISSUE THREAD

**Issue by zauster** [paulofelipe/cp2015#1]
Hey Paulo,

first of all: congrats to this very nice and fast implementation of the model!

I would like to use your project for research I am doing, but have a question concerning the technical efficiency term in the welfare decomposition: is there a paper that shows the derivation of this additional term or can you motivate how you can include this term?

Thanks for your time!

Kind regards,

Oliver

**Comment by paulofelipe** [comment]
Hi @zauster ,

Thanks for the question. This derivation is not presented in any paper. I've just followed the derivation presented by Caliendo and Parro (2015) in Appendix B. The technical efficiency term is not presented in the original formula (Equation 16) because they assume that there is no variation in the $d_{ni}^j$ variable. If we assume a change in this variable, we have to modify the Equation B2 to
$$\mathop{d}\ln P_n = \sum_{j = 1}^J \alpha_n^j \sum_{i = 1}^N \pi_{ni}^j \left(\mathop{d}\ln c_i^j +  \mathop{d} \ln d_{ni}^j  + \mathop{d} \ln {\tilde{\tau}_{ni}^j} \right).$$

Then, follow the derivation presented in Appendix B to derive a new version of Equation 16 with this additional term.

Please let me know if you have any questions about my explanation.

Best regards,

Paulo

**Comment by zauster** [comment]
Thanks, that explanation makes it perfectly clear.

Have you already used this technical efficiency term in your work? Because my next question would be how do you get/estimate a value for the change in trade costs (a ratified free trade agreement, abolished non-tariff measures)?

**Comment by paulofelipe** [comment]
Hi @zauster ,

I think this paper conducts an experiment similar to the one you are interested in: https://www.ifo.de/DocDL/wp-2016-219-aichele-felbemayr-heiland-welfare-ttip.pdf 

It is possible to set the relative change of the variable $d_{ni}^j$ after you have estimated the change in trade costs.

**Comment by zauster** [comment]
Ah yes, thanks. They take estimates for the change in trade costs from a gravity estimation
